
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
test_add (test_mathfunc.TestMathFunc) ... skipped "i don't want to run this case."
test_minus (test_mathfunc.TestMathFunc) ... ok
test_divide (test_mathfunc.TestMathFunc) ... FAIL

======================================================================
FAIL: test_divide (test_mathfunc.TestMathFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\learn-python3\python_book_scripts\11_unittest\test_mathfunc.py", line 19, in test_divide
    self.assertEqual(2, divide(5, 2))
AssertionError: 2 != 2.5

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (failures=1, skipped=1)
